version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-futbot
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 'futbot_db'    
      MYSQL_USER: futbot
      MYSQL_PASSWORD: futbot123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_data:
